apiVersion: apps/v1
kind: Deployment
metadata:
  name: draw
  namespace: ricky
spec:
  selector:
    matchLabels:
      app: draw
  replicas: 1
  template:
    metadata:
      labels:
        app: draw
    spec:
      containers:
        - name: draw
          image: yshua5631/draw:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80 #容器开放的端口，即使是80也要显示指定
            - containerPort: 443 # 也开放了https端口
            - containerPort: 5000 # 也开放了https端口
---

apiVersion: v1
kind: Service
metadata:
  name: draw-svc
  namespace: ricky
spec:
  ports:
    - port: 80 # 集群内部可以访问的端口. 备注  -p 20180:80， 80代表容器端口，20180代表主机端口
      targetPort: 80 # Docker实例的端口 - 最保守的
      #nodePort: 31280  # 暴露给外网的端口
      protocol: TCP
      name: http
    - port: 5000 # 集群内部可以访问的端口. 备注  -p 20180:80， 80代表容器端口，20180代表主机端口
      targetPort: 5000 # Docker实例的端口 - 最保守的
      #nodePort: 31280  # 暴露给外网的端口
      protocol: TCP
      name: real-port
# type: NodePort # k8s会向外网暴露端口，如果是在阿里云上，阿里云需要将相应的端口设置成白名单
  selector:
    app: draw
